FROM php:7.2-apache

COPY vhost.conf /etc/apache2/sites-available/000-default.conf
COPY server.crt /etc/apache2/ssl/server.crt
COPY server.key /etc/apache2/ssl/server.key

# Update apt
RUN apt-get update -qq
RUN apt-get upgrade -qqy

# Install zip extension
RUN apt-get install -y libzip-dev zip
RUN docker-php-ext-install zip

# Get packages
RUN apt-get install -y wget gnupg curl openssh-client rsync grsync git libicu-dev libxslt-dev
RUN apt-get install -y --no-install-recommends git
RUN docker-php-ext-install pdo pdo_mysql mysqli intl xsl bcmath ctype json

# Install GD
RUN apt-get install -y libwebp-dev libjpeg-dev libpng-dev libxpm-dev libfreetype6-dev
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
RUN docker-php-ext-install gd

# Get Node.js
RUN curl -sL https://deb.nodesource.com/setup_13.x | bash -
RUN apt install -y --no-install-recommends nodejs
RUN npm install -g npm@latest

# Get Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --filename=composer --install-dir=/usr/local/bin
RUN php -r "unlink('composer-setup.php');"

# Active mod_rewrite & mod_ssl
RUN a2enmod rewrite
RUN a2enmod ssl